-- Cria a tabela price_history (histórico de preços)
CREATE TABLE IF NOT EXISTS price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    category TEXT,
    price NUMERIC(10, 2),
    installment_price NUMERIC(10, 2),
    store TEXT NOT NULL,
    url TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Índice para buscas mais rápidas por nome do produto e data
CREATE INDEX IF NOT EXISTS idx_price_history_product_name ON price_history (product_name);
CREATE INDEX IF NOT EXISTS idx_price_history_timestamp ON price_history (timestamp);
